import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styled from "styled-components";
import styles from "@styles/Home.module.css";
import Footer from "@components/footer/Footer";
import AboutSectionLayout from "@components/layout/AboutSectionLayout";
import HomeLayout from "@components/layout/HomeLayout";
import ScrollSuggestor from "@components/ScrollSuggestor";

const HomeWrapper = styled.div`
  flex-grow: 1;
`;

const StyledImage = styled(Image)`
  z-index: -1;
`;

const ImageWrapper = styled.div`
  position: absolute;
  height: 100%;
  width: 800px;
  right: 0;
`;

const HomeSection = styled.section`
  height: 100vh;
`;

const AboutSection = styled.section`
  height: 100vh;
`;

const Home: NextPage = () => {
  return (
    <HomeLayout
      topSection={
        <HomeSection>
          <ImageWrapper>
            <StyledImage
              src="/images/EngelbyteAmCoden.png"
              layout="fill"
              priority={true}
              objectFit="contain"
            />
          </ImageWrapper>
          <ScrollSuggestor />
        </HomeSection>
      }
    >
      <HomeWrapper>
        <Head>
          <title>waterbyte</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <AboutSection>
          <AboutSectionLayout
            vertical="Wer?"
            largeText="Entwicklungszentrale der hellsten Köpfe des Mittelmeerraums."
            content="Aus jahrelanger Erfahrung in der selben Branche kristallisierten sich aus einer Gemenge von Schülern die dem Waterbyte Ideal einst am ehesten entsprachen eine Gruppierung von unglaublicher Einzigartigkeit."
          >
            animation
          </AboutSectionLayout>
        </AboutSection>
      </HomeWrapper>
    </HomeLayout>
  );
};

export default Home;
