import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styled from "styled-components";
import styles from "@styles/Home.module.css";
import Footer from "@components/footer/Footer";
import AboutSectionLayout from "@components/layout/AboutSectionLayout";
import HomeLayout from "@components/layout/HomeLayout";
import ScrollSuggestor from "@components/ScrollSuggestor";

const HomeWrapper = styled.div`
  flex-grow: 1;
`;

const StyledImage = styled(Image)`
  z-index: -1;
`;

const ImageWrapper = styled.div`
  position: absolute;
  height: 100%;
  width: 800px;
  right: 0;
`;

const HomeSection = styled.section`
  height: 100vh;
`;

const AboutSection = styled.section`
  height: fit-content;

`;

const Home: NextPage = () => {
  return (
    <HomeLayout
      topSection={
        <HomeSection>
          <ImageWrapper>
            <StyledImage
              src="/images/EngelbyteAmCoden.png"
              layout="fill"
              priority={true}
              objectFit="contain"
            />
          </ImageWrapper>
          <ScrollSuggestor />
        </HomeSection>
      }
    >
      <HomeWrapper>
        <Head>
          <title>waterbyte</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <AboutSection>
          <AboutSectionLayout
            vertical="Wer?"
            largeText="Entwicklungszentrale der hellsten Köpfe des Mittelmeerraums."
            content="Aus jahrelanger Erfahrung in der selben Branche kristallisierten sich aus einer Gemenge von Schülern die dem Waterbyte Ideal einst am ehesten entsprachen eine Gruppierung von unglaublicher Einzigartigkeit."
          >
            animation
          </AboutSectionLayout>
          <AboutSectionLayout
            vertical="Woher?"
            largeText="Wo keimten die ersten Sprossen des Jungspundverbands?"
            content="Die Lehranstalt Grieskirchen vereinte einst einen Haufen diverser von diversen Knaben von welchen sich wiederum eine handvoll mit Waterbyte identifizierten. "
          >
            animation
          </AboutSectionLayout>
          <AboutSectionLayout
            vertical="Tätigkeit?"
            largeText="Entwicklungszentrale der hellsten Köpfe des Mittelmeerraums."
            content="Bei Waterbyte drehte sich einst alles um die Befriedigung unseres Vorgesetzten: Lehrer Gertsch! 
            Eines Tages wurde sich jedoch dazu entschlossen sich aus der Dokumentations-handschelle zu befreien und frei Projekte in Angriff zu nehmen. Darauf entsprangen gleich die ersten Projekte welche sich durch grenzgeniale Kodierungsleistungen auszeichneten. Um dieses Potenzial aufrecht zu erhalten, definiert sich der Alltag bei Waterbyte auch durch die erstellung von Medien, welche Einerseits Einblicke in den Verein, aber auch externe Thematiken umfassen. Zu aktuellem Stand verfügen wir eine Blog-Infrastruktur, welche durch ein Sticker-arsenal und einen Store erweitert werden soll. Auch Events für die Zelebrierung der Gemeinschaft finden hohe Priorität in die Zeitplanung jedes Mitglieds. "
          >
            animation
          </AboutSectionLayout>
          <AboutSectionLayout
            vertical="Strategie?"
            largeText="Entwicklungszentrale der hellsten Köpfe des Mittelmeerraums."
            content="Aus jahrelanger Erfahrung in der selben Branche kristallisierten sich aus einer Gemenge von Schülern die dem Waterbyte Ideal einst am ehesten entsprachen eine Gruppierung von unglaublicher Einzigartigkeit."
          >
            animation
          </AboutSectionLayout>
          <AboutSectionLayout
            vertical="Kontakt!"
            largeText="Entwicklungszentrale der hellsten Köpfe des Mittelmeerraums."
            content="Aus jahrelanger Erfahrung in der selben Branche kristallisierten sich aus einer Gemenge von Schülern die dem Waterbyte Ideal einst am ehesten entsprachen eine Gruppierung von unglaublicher Einzigartigkeit."
          >
            animation
          </AboutSectionLayout>
        </AboutSection>
      </HomeWrapper>
    </HomeLayout>
  );
};

export default Home;
